### ISSUE TITLE
Autotest

### ISSUE THREAD

**Issue by AlekzzR** [Dreamer48k/PySeleniumWebDriver#1]

**Comment by Dreamer48k** [comment]
Привет,
что за вопрос?

сб, 11 сент. 2021 г. в 13:32, AlekzzR ***@***.***>:

**Comment by AlekzzR** [comment]
Их несколько)
1. Взяли ли в итоге в тензор?)
2.  Код в репозитории претерпел изменения уже после отказа?

Было бы здорово поощаться не здесь, если есть возможность

**Comment by Dreamer48k** [comment]
Пиши сюда
https://vk.com/id431812920

сб, 11 сент. 2021 г. в 14:08, AlekzzR ***@***.***>:
